Algoritmo "PROGRAMA 15. VALORES2 - GABRIEL MARQUES"

Var
// Seção de Declarações das variáveis 
valor1,valor2,soma,dif1,dife2,multi,dov1,dov2:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Por favor,informe um valor : ")
leia(valor1)
escreva(" Agora informe o segundo valor : ")
leia(valor2)

soma <- (valor1+valor2)
dif1 <- (valor2-valor1)
dife2 <- (valor1-valor2)
multi <- (valor1*valor2)
dov1 <- (valor2:valor1)
dov2 <- (valor1:valor2)


Fimalgoritmo