Algoritmo "PROGRAMA 13. PESO E ALTURA - GABRIEL MARQUES"

Var
// Seção de Declarações das variáveis 
 peso,altura,resultado1,resultado2:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("Por favor , informe seu peso em kg : ")
 leia(peso)
 escreva("Agora informe sua altura em metros :")
 leia(altura)
 
 resultado1 <- (peso*1000)
 resultado2 <- (altura*100)
 
 escreva(" Tu possuis " ,resultado1, " gramas e " ,resultado2, " centímetros ")

Fimalgoritmo