Algoritmo "PROGRAMA 17. PRESTACAO - GABRIEL MARQUES"

Var
// Seção de Declarações das variáveis 
valor1,valor2,resultado1:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Por favor , informe o valor de pagamento :")
leia(valor1)
escreva("Agora informe o número de prestações : ")
leia(valor2)

resultado1 <- (valor1:valor2)

escreva("O valor de cada prestação será : ",resultado1,)

Fimalgoritmo