Algoritmo "PROGRAMA 19. ANOS - GABRIEL MARQUES"

Var
// Seção de Declarações das variáveis 
anos,meses,dias,resultado:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Por favor , informe sua idade em anos : ")
leia(anos)
escreva("Agora os meses de idade : " )
leia(meses)
escreva("Informe sua idade em dias :")
leia(dias)

resultado <- (anos*30*12 + meses*30 + dias)

escreva("Sua idade , em dias , é : " ,resultado,)

Fimalgoritmo