Algoritmo " PROGRAMA VALORES - GABRIEL MARQUES "

Var
// Seção de Declarações das variáveis 
valor,valor2,valor3:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Por favor , informe um valor :")
leia(valor)

valor2<- RaizQ(valor)
valor3<- (valor^2)

escreva(" O valor escolhido é : " ,valor, )

escreva("O seu quadrado é :" ,valor3, )

escreva("E sua raiz é:" ,valor2, )



Fimalgoritmo