Algoritmo "PROGRAMA KM E L - GABRIEL MARQUES"

Var
// Seção de Declarações das variáveis
km,l,resultado:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Por favor , informe quantos km serão percorridos: " )
leia(km)
escreva("Agora informe o valor de litros por quilômetro: " )
leia(l)

resultado<- km*l

escreva(" O resultado de litros gastos é : " ,resultado, )

Fimalgoritmo