Algoritmo "PROGRAMA 25.CILINDRO-GABRIEL MARQUES"


Var
// Seção de Declarações das variáveis 
raio1,altura2,resultado1:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Por favor , informe a altura do cilindro:")
leia(altura2)
escreva("Agora informe a raio do círculo: " )
leia(raio1)

resultado1<- 3.14159265*(raio1*raio1)*altura2
escreva(" O volume é : " ,resultado1, )

Fimalgoritmo