Algoritmo "PROGRAMA 27.HIPOTENUSA-GABRIEL MARQUES"

Var
// Seção de Declarações das variáveis 
valor1,valor2,resultado1:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Por favor , informe o valor do cateto1:")
leia(valor1)
escreva(" Agora informe o valor do cateto2:")
leia(valor2)

resultado1<- raizQ((valor1*valor1)+(valor2*valor2))
escreva("A Hipotenusa é: " ,resultado1,)

Fimalgoritmo